import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '@/app/styles/app.css';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Chatting Message Generator',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ko'>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
